# 2.3.1 标量

In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

# 2.3.2 向量

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

# 2.3.2.1. 长度、维度和形状

In [5]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

# 2.3.3 矩阵

In [7]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

# 2.3.4 张量

In [11]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

# 2.3.5 张量的运算

In [12]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [13]:
#矩阵按元素相乘
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X,a + X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

# 2.3.6. 降维

In [15]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [16]:
A.shape, A.sum(),A

(torch.Size([5, 4]),
 tensor(190.),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [17]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [18]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [19]:
A.sum(axis=[0, 1])  # 结果和A.sum()相同

tensor(190.)

In [20]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

# 2.3.6.1. 非降维求和

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [22]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [23]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [24]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

# 2.3.7. 点积

In [25]:
x

tensor([0., 1., 2., 3.])

In [26]:
y = torch.ones_like(x)
y

tensor([1., 1., 1., 1.])

In [27]:
torch.dot(x, y)

tensor(6.)

In [28]:
torch.sum(x * y)

tensor(6.)

# 2.3.8 矩阵向量积

In [32]:
A.shape, x.shape,A,x

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [30]:
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

# 2.3.9. 矩阵乘法

In [34]:
b = torch.ones(4,3)
mm = torch.mm(A, b)
mm

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

# 2.3.10. 范数

In [35]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [36]:
torch.abs(u).sum()

tensor(7.)

# 练习证明一个矩阵的转置的转置等于原矩阵

In [37]:
A.T.T == A

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [38]:
B = torch.rand_like(A)
B

tensor([[0.6352, 0.5536, 0.9432, 0.1132],
        [0.3777, 0.2925, 0.5683, 0.0255],
        [0.9693, 0.9627, 0.1262, 0.5555],
        [0.7073, 0.4229, 0.7472, 0.8298],
        [0.3882, 0.6190, 0.4666, 0.9989]])

# 练习证明两个矩阵的转置的和等于它们的和的转置

In [40]:
A_T = A.T
B_T = B.T
A_T+B_T

tensor([[ 0.6352,  4.3777,  8.9693, 12.7073, 16.3882],
        [ 1.5536,  5.2925,  9.9627, 13.4229, 17.6190],
        [ 2.9432,  6.5683, 10.1262, 14.7472, 18.4666],
        [ 3.1132,  7.0255, 11.5555, 15.8298, 19.9989]])

In [41]:
(A+B).T == A_T+B_T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

# 练习任意一个方阵+其转置是对称矩阵

In [42]:
a = torch.rand(3,3)
a+a.T ==(a+a.T).T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [43]:
X = torch.rand(2,3,4)
X

tensor([[[0.7857, 0.7216, 0.3211, 0.9874],
         [0.8807, 0.4094, 0.3007, 0.8829],
         [0.3832, 0.0611, 0.5438, 0.9251]],

        [[0.4531, 0.8041, 0.8656, 0.0251],
         [0.4090, 0.4254, 0.1075, 0.9064],
         [0.5447, 0.7479, 0.4666, 0.5041]]])

In [44]:
#len(X),返回轴0的长度
len(X)

2

In [56]:
A=torch.rand(4,4)*10
A

tensor([[3.5841, 2.5681, 6.5254, 9.9032],
        [3.8716, 0.2362, 6.6505, 3.1433],
        [1.0963, 9.3407, 5.6625, 9.1014],
        [4.5219, 9.9612, 9.5105, 8.4904]])

In [58]:
A/A.sum()

tensor([[0.0381, 0.0273, 0.0693, 0.1052],
        [0.0411, 0.0025, 0.0706, 0.0334],
        [0.0116, 0.0992, 0.0601, 0.0967],
        [0.0480, 0.1058, 0.1010, 0.0902]])

In [59]:
A/A.sum(axis=0)

tensor([[0.2741, 0.1162, 0.2302, 0.3232],
        [0.2961, 0.0107, 0.2346, 0.1026],
        [0.0839, 0.4225, 0.1997, 0.2971],
        [0.3459, 0.4506, 0.3355, 0.2771]])

In [60]:
A.sum(axis=1)

tensor([22.5808, 13.9016, 25.2009, 32.4840])

In [62]:
A/A.sum(axis=1,keepdims=True)

tensor([[0.1587, 0.1137, 0.2890, 0.4386],
        [0.2785, 0.0170, 0.4784, 0.2261],
        [0.0435, 0.3706, 0.2247, 0.3612],
        [0.1392, 0.3066, 0.2928, 0.2614]])

In [63]:
0.1587+0.1137+0.2890+0.4368

0.9982

In [64]:
a = torch.rand(2,3,4)
a

tensor([[[0.7141, 0.1559, 0.3700, 0.0232],
         [0.2727, 0.7225, 0.7189, 0.3246],
         [0.9182, 0.5547, 0.6050, 0.2175]],

        [[0.9412, 0.4193, 0.6631, 0.4390],
         [0.1873, 0.2051, 0.5616, 0.8824],
         [0.1270, 0.6377, 0.6275, 0.8738]]])

In [65]:
sum_0 = a.sum(axis=0)
sum_0

tensor([[1.6553, 0.5751, 1.0331, 0.4622],
        [0.4600, 0.9276, 1.2805, 1.2070],
        [1.0452, 1.1924, 1.2326, 1.0913]])

In [66]:
sum_1 = a.sum(axis=1)
sum_1

tensor([[1.9050, 1.4330, 1.6940, 0.5653],
        [1.2555, 1.2621, 1.8522, 2.1953]])

In [67]:
sum_2 = a.sum(axis=2)
sum_2

tensor([[1.2631, 2.0387, 2.2955],
        [2.4626, 1.8364, 2.2661]])