In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
def coucev():
    #初始化CountVectorizer
    vectorizer = CountVectorizer(min_df=2)
    #加载数据集
    data = ['apple apple pie', 'banana banana ice cream', 'apple pie', 'banana ice cream']
    #转换成词频矩阵
    X = vectorizer.fit_transform(data)
    #打印数据集
    print(X)
    #打印数据类型
    print(type(X))
    #获取词袋模型中的所有词汇
    words = vectorizer.get_feature_names_out()
    #打印词频矩阵
    print(X.toarray())
    #打印所有词汇
    print(words)

coucev()

  (np.int32(0), np.int32(0))	2
  (np.int32(0), np.int32(4))	1
  (np.int32(1), np.int32(1))	2
  (np.int32(1), np.int32(3))	1
  (np.int32(1), np.int32(2))	1
  (np.int32(2), np.int32(0))	1
  (np.int32(2), np.int32(4))	1
  (np.int32(3), np.int32(1))	1
  (np.int32(3), np.int32(3))	1
  (np.int32(3), np.int32(2))	1
<class 'scipy.sparse._csr.csr_matrix'>
[[2 0 0 0 1]
 [0 2 1 1 0]
 [1 0 0 0 1]
 [0 1 1 1 0]]
['apple' 'banana' 'cream' 'ice' 'pie']
