In [3]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [8]:
def stand():
    std = StandardScaler()
    data = np.random.rand(16).reshape(4, 4)
    print("原始数据：")
    print(data)
    print('-'*50)
    data_std = std.fit_transform(data)
    print("标准化后的数据：")
    print(data_std)
    print('-'*50)
    print("均值：")
    print(std.mean_)
    print('-'*50)
    print("方差：")
    print(std.var_)
    print('-'*50)

stand()

原始数据：
[[0.20182155 0.84439979 0.00471694 0.20145795]
 [0.08994015 0.96585685 0.30254072 0.15675107]
 [0.00393592 0.01483069 0.95296041 0.62211983]
 [0.19574989 0.083898   0.90644072 0.5432334 ]]
--------------------------------------------------
标准化后的数据：
[[ 0.96510491  0.85240981 -1.3343469  -0.87820805]
 [-0.40239423  1.13439324 -0.59423721 -1.09701969]
 [-1.45360313 -1.07357733  1.02209415  1.18066322]
 [ 0.89089244 -0.91322571  0.90648996  0.79456452]]
--------------------------------------------------
均值：
[0.12286188 0.47724633 0.54166469 0.38089056]
--------------------------------------------------
方差：
[0.00669363 0.18552326 0.16192972 0.04174533]
--------------------------------------------------
缩放因子：
[0.0818146  0.43072411 0.40240492 0.20431675]
