In [5]:
from sklearn.feature_selection import VarianceThreshold
import numpy as np

In [10]:
def varance():
    data = np.random.rand(24).reshape(2, 12)
    var = VarianceThreshold(threshold=0.1)
    data_var = var.fit_transform(data)
    print(data_var)
    print(var.get_feature_names_out())
    print(var.get_support(True))
varance()

[[0.97734236 0.06102474 0.96963517]
 [0.24928657 0.87051339 0.02025034]]
['x0' 'x5' 'x6']
[0 5 6]
